// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ClockPanel(Props) {
  return React.createElement("div", {
              className: "clock-panel"
            });
}

var make = ClockPanel;

exports.make = make;
/* react Not a pure module */
