// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Utils$ReactHooksTemplate = require("../Utils.bs.js");
var ToggleInfo$ReactHooksTemplate = require("./ToggleInfo.bs.js");

function InfoPanel(Props) {
  var show = Props.show;
  var toggleInfo = Props.toggleInfo;
  var toggleClass = Utils$ReactHooksTemplate.c(/* array */[
        /* tuple */[
          "info-panel",
          true
        ],
        /* tuple */[
          "info-panel--active",
          show
        ]
      ]);
  return React.createElement("div", {
              className: toggleClass
            }, React.createElement("div", {
                  className: "info-panel__navigation"
                }, React.createElement("div", {
                      className: "info-panel__toggle"
                    }, React.createElement(ToggleInfo$ReactHooksTemplate.make, {
                          toggleInfo: toggleInfo
                        }))), React.createElement("div", {
                  className: "info-panel__content"
                }));
}

var make = InfoPanel;

exports.make = make;
/* react Not a pure module */
