// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function InfoPanel(Props) {
  return React.createElement("div", {
              className: "info-panel"
            }, React.createElement("div", {
                  className: "info-panel__navigation"
                }), React.createElement("div", {
                  className: "info-panel__content"
                }));
}

var make = InfoPanel;

exports.make = make;
/* react Not a pure module */
