// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function ToggleInfo(Props) {
  var toggleInfo = Props.toggleInfo;
  var onClick = function (evt_) {
    return Curry._1(toggleInfo, /* () */0);
  };
  return React.createElement("div", {
              className: "toggle-info"
            }, React.createElement("button", {
                  onClick: onClick
                }, "Toggle"));
}

var make = ToggleInfo;

exports.make = make;
/* react Not a pure module */
