// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

((require('./styles/app.scss')));

function App(Props) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement("h2", undefined, "App"));
}

var make = App;

exports.make = make;
/*  Not a pure module */
