// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Pomodoro$ReactHooksTemplate = require("./components/Pomodoro.bs.js");

((require('./styles/app.scss')));

function Index$App(Props) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement(Pomodoro$ReactHooksTemplate.make, { }));
}

var App = /* module */[/* make */Index$App];

ReactDOMRe.renderToElementWithId(React.createElement(Index$App, { }), "app");

exports.App = App;
/*  Not a pure module */
