// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function c(cls) {
  return List.fold_left((function (class_, prop) {
                var match = class_ === "";
                if (match) {
                  return prop;
                } else {
                  return class_ + (" " + prop);
                }
              }), "", List.map((function (param) {
                    return param[0];
                  }), List.filter((function (param) {
                          return param[1] === true;
                        }))(cls)));
}

exports.c = c;
/* No side effect */
