// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function concat(prim, prim$1) {
  return prim$1.concat(prim);
}

function c(cls) {
  return cls.reduce((function (result, p) {
                  var match = p[1] === true;
                  if (match) {
                    return /* array */[p[0]].concat(result);
                  } else {
                    return result;
                  }
                }), /* array */[]).join(" ");
}

exports.concat = concat;
exports.c = c;
/* No side effect */
